# Create environment: conda env create --file environment.yml
# Activate environment: conda activate nm-dev
# Deactivate environment: conda deactivate
# To remove environment: conda remove --name nm-dev --all
# To verify that the environment was removed: conda info --envs

name: nm-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy
  - matplotlib
  - scipy
  - pandas
  - seaborn
  - pytest
  - autopep8
  - isort
  - yapf
  - nest-simulator=2.20.2=*
  - pip:
    - pytest
    - neo
    - elephant
    - quantities
    - viziphant
    - pydot
