# Create environment: conda env create --file environment.yml
# Activate environment: conda activate nm-dev
# Deactivate environment: conda deactivate
# To remove environment: conda remove --name nm-dev --all
# To verify that the environment was removed: conda info --envs

name: nm-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.8
  - pip
  - numpy
  - matplotlib
  - scipy
  - pandas
  - seaborn
  - numba
  - cython
  - pytest
  - autopep8
  - isort
  - yapf
  - scikit-learn
  - jupyter
  - jupyter_contrib_nbextensions
  - cython
  - nest-simulator
  #- nest-simulator=*=mpi_openmpi*
  - lfpy
